<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Campfire.RailsCompat/Campfire.RailsCompat.csproj" />
    <ProjectReference Include="../Campfire.Vectors/Campfire.Vectors.csproj" />
  </ItemGroup>

</Project>
