<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Campfire.Web/Campfire.Web.csproj" />
    <ProjectReference Include="../Campfire.Cable.Tests/Campfire.Cable.Tests.csproj" />
    <ProjectReference Include="../Campfire.Vectors/Campfire.Vectors.csproj" />
  </ItemGroup>

</Project>
