# Writes MarcelExtensions.g.cs: Marcel's extension => type table and each type's extensions, as
# the reference bundle's marcel (1.1.0, reference/Gemfile.lock) holds them once its definitions load.
#
#   gem install marcel -v 1.1.0
#   ruby src/Campfire.Storage/Variants/marcel_extensions.rb
gem "marcel", "1.1.0"
require "marcel"

def literal(string) = string.dump

out = +<<~CS
  // <auto-generated>
  // Generated by src/Campfire.Storage/Variants/marcel_extensions.rb from marcel #{Marcel::VERSION}. Do not edit.
  // </auto-generated>
  using System.Collections.Frozen;

  namespace Campfire.Storage.Variants;

  static partial class MarcelExtensions
  {
      /// <summary><c>Marcel::EXTENSIONS</c>: extension => type.</summary>
      static readonly FrozenDictionary<string, string> Types = new Dictionary<string, string>(StringComparer.Ordinal)
      {
CS
Marcel::EXTENSIONS.sort.each { |ext, type| out << "        [#{literal(ext)}] = #{literal(type)},\n" }
out << <<~CS.gsub(/^/, "    ")
  }.ToFrozenDictionary(StringComparer.Ordinal);

  /// <summary><c>Marcel::TYPE_EXTS</c>: type => extensions, first one first.</summary>
  static readonly FrozenDictionary<string, string[]> TypeExtensions = new Dictionary<string, string[]>(StringComparer.Ordinal)
  {
CS
Marcel::TYPE_EXTS.sort.each { |type, exts| out << "        [#{literal(type)}] = [#{Array(exts).map { literal(_1) }.join(", ")}],\n" }
out << "    }.ToFrozenDictionary(StringComparer.Ordinal);\n}\n"

File.write File.join(__dir__, "MarcelExtensions.g.cs"), out
