using System.Text;
using Campfire.Web.Routing;

namespace Campfire.Web.Tests.Routing;

/// <summary>
/// Writes <c>src/Campfire.Web/Routes.g.cs</c> from the reference's route table: every route in
/// Rails order with its handler hook, and a <c>_path</c>/<c>_url</c> helper pair per named route.
/// <see cref="RoutesSourceTests"/> fails when the checked-in file differs; regenerate it with
/// <c>UPDATE_ROUTES=1 dotnet test tests/Campfire.Web.Tests --filter RoutesSourceTests</c>.
/// </summary>
public static class RoutesSource
{
    /// <summary>
    /// Controllers the reference routes to but doesn't define: <c>recognize_path</c> raises for
    /// them, and serving them is a 500 (<see cref="MissingControllerException"/>).
    /// </summary>
    public static readonly IReadOnlySet<string> MissingControllers = new HashSet<string> { "rooms/settings" };

    public static string Generate(IReadOnlyList<NamedRoute> routes)
    {
        var source = new StringBuilder();
        source.Append("""
            // <auto-generated>
            // Generated by tests/Campfire.Web.Tests/Routing/RoutesSource.cs from
            // tests/Campfire.Web.Tests/Routing/Vectors/routes.json: vectors/campfire_routes.json with the
            // reference's route names. Don't edit it; regenerate it with
            //   UPDATE_ROUTES=1 dotnet test tests/Campfire.Web.Tests --filter RoutesSourceTests
            // </auto-generated>
            #nullable enable

            using Campfire.Web.Routing;
            using Microsoft.AspNetCore.Http;

            namespace Campfire.Web;

            /// <summary>
            /// The reference's routes (<c>bin/rails routes</c>, in order) and their URL helpers. A feature
            /// binds its handler by implementing the route's hook in its own file:
            /// <code>
            /// static partial class Routes
            /// {
            ///     static partial void RoomsShow(ref RequestDelegate? handler) => handler = RoomsController.Show;
            /// }
            /// </code>
            /// Routes without a handler answer 501.
            /// </summary>
            public static partial class Routes
            {
                static readonly KeyValuePair<string, string>[] FormatJson = [new("format", "json")];
                static readonly KeyValuePair<string, string>[] UserIdMe = [new("user_id", "me")];

                /// <summary>Every route, in <c>config/routes.rb</c> order (engines' routes last).</summary>
                public static IReadOnlyList<RouteDefinition> Definitions { get; } =
                [

            """);
        foreach (var route in routes)
        {
            source.Append("        new(")
                .Append(Literal(route.Verb)).Append(", ")
                .Append(Literal(route.Path)).Append(", ")
                .Append(Literal(route.Endpoint)).Append(", ")
                .Append(route.Name is null ? "null" : Literal(route.Name));
            var defaults = DefaultsField(route.Defaults);
            if (defaults is not null)
            {
                source.Append(", ").Append(defaults);
            }
            source.Append("),\n");
        }
        source.Append("""
                ];

                /// <summary>The route table, with each route bound to its handler or the 501 stub.</summary>
                public static RouteTable Table { get; } = new(Definitions, definition => Handler(definition.Endpoint));

                static RequestDelegate? Handler(string endpoint)
                {
                    RequestDelegate? handler = null;
                    switch (endpoint)
                    {

            """);
        foreach (var endpoint in routes.Select(route => route.Endpoint).Distinct())
        {
            var controller = endpoint[..endpoint.IndexOf('#', StringComparison.Ordinal)];
            source.Append("            case ").Append(Literal(endpoint)).Append(": ");
            source.Append(MissingControllers.Contains(controller)
                ? "handler = MissingController; break;\n"
                : $"{HookName(endpoint)}(ref handler); break;\n");
        }
        source.Append("""
                    }
                    return handler;
                }

                static Task MissingController(HttpContext context) =>
                    throw new MissingControllerException("uninitialized constant " + context.RailsRequest().Route?.Controller);

            """);

        foreach (var endpoint in routes.Select(route => route.Endpoint).Distinct())
        {
            if (MissingControllers.Contains(endpoint[..endpoint.IndexOf('#', StringComparison.Ordinal)]))
            {
                continue;
            }
            var verbs = routes.Where(route => route.Endpoint == endpoint).Select(route => $"{route.Verb} {route.Path}");
            source.Append("\n    /// <summary>").Append(Xml(endpoint)).Append(": ").Append(Xml(string.Join(", ", verbs))).Append("</summary>\n");
            source.Append("    static partial void ").Append(HookName(endpoint)).Append("(ref RequestDelegate? handler);\n");
        }

        for (var index = 0; index < routes.Count; index++)
        {
            if (routes[index].Name is { } name)
            {
                AppendHelpers(source, index, name, routes[index]);
            }
        }
        source.Append("}\n");
        return source.ToString();
    }

    /// <summary>The hook a feature implements for <paramref name="endpoint"/>: <c>users/push_subscriptions#index</c> is <c>UsersPushSubscriptionsIndex</c>.</summary>
    public static string HookName(string endpoint) => Pascal(endpoint.Replace('#', '_').Replace('/', '_'));

    /// <summary>The C# helper for a route name: <c>room_messages</c> is <c>RoomMessagesPath</c>/<c>RoomMessagesUrl</c>.</summary>
    public static string HelperName(string name, string suffix) => Pascal(name) + suffix;

    static void AppendHelpers(StringBuilder source, int index, string name, NamedRoute route)
    {
        var spec = RouteSpec.Parse(route.Path);
        var required = spec.RequiredNames;
        var overloads = new List<IReadOnlyList<string>> { required };
        var withoutDefaults = required.Where(segment => !route.Defaults.ContainsKey(segment)).ToList();
        if (withoutDefaults.Count < required.Count)
        {
            overloads.Add(withoutDefaults);
        }

        foreach (var parameters in overloads)
        {
            var signature = string.Concat(parameters.Select(parameter => $"object? {Camel(parameter)}, "));
            var arguments = string.Join(", ", parameters.Select(Camel));
            source.Append($"\n    /// <summary><c>{name}_path</c>: {Xml(route.Verb)} {Xml(route.Path)} ({Xml(route.Endpoint)})</summary>\n");
            source.Append($"    public static string {HelperName(name, "Path")}({signature}RouteOptions? options = null) =>\n");
            source.Append($"        UrlGenerator.Path(Table.Routes[{index}], [{arguments}], options);\n");
            source.Append($"\n    /// <summary><c>{name}_url</c>: {Xml(route.Verb)} {Xml(route.Path)} ({Xml(route.Endpoint)})</summary>\n");
            source.Append($"    public static string {HelperName(name, "Url")}(UrlBase origin, {signature}RouteOptions? options = null) =>\n");
            source.Append($"        UrlGenerator.Url(origin, Table.Routes[{index}], [{arguments}], options);\n");
        }
    }

    static string? DefaultsField(IReadOnlyDictionary<string, string> defaults) => defaults.Count switch
    {
        0 => null,
        1 when defaults.TryGetValue("format", out var format) && format == "json" => "FormatJson",
        1 when defaults.TryGetValue("user_id", out var user) && user == "me" => "UserIdMe",
        _ => throw new InvalidOperationException($"Unexpected route defaults: {string.Join(", ", defaults)}"),
    };

    static string Pascal(string snake) =>
        string.Concat(snake.Split('_', StringSplitOptions.RemoveEmptyEntries).Select(word => char.ToUpperInvariant(word[0]) + word[1..]));

    static string Camel(string snake)
    {
        var pascal = Pascal(snake);
        return char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }

    static string Literal(string value) => "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    static string Xml(string value) => System.Security.SecurityElement.Escape(value);
}
