# Writes src/Campfire.Storage/Blobs/Approximations.cs: I18n's default transliteration table, which
# ActionDispatch::Http::ContentDisposition uses for the ASCII `filename=` parameter.
#
#   bundle exec ruby approximations.rb > ../../../src/Campfire.Storage/Blobs/Approximations.cs
require "i18n"

table = I18n::Backend::Transliterator::HashTransliterator::DEFAULT_APPROXIMATIONS
puts "// <auto-generated>"
puts "// Generated by tests/Campfire.Storage.Tests/Oracle/approximations.rb from i18n #{I18n::VERSION}."
puts "// </auto-generated>"
puts
puts "using System.Collections.Frozen;"
puts
puts "namespace Campfire.Storage.Blobs;"
puts
puts "static class Approximations"
puts "{"
puts "    /// <summary><c>I18n::Backend::Transliterator::HashTransliterator::DEFAULT_APPROXIMATIONS</c>.</summary>"
puts "    public static readonly IReadOnlyDictionary<char, string> Default = new Dictionary<char, string>"
puts "    {"
table.each do |char, ascii|
  puts format("        ['\\u%04X'] = %s,", char.ord, ascii.inspect)
end
puts "    }.ToFrozenDictionary();"
puts "}"
