# Writes MarcelMagic.g.cs: Marcel's magic number table (in lookup order) and type parents, as the
# reference bundle's marcel (1.1.0, reference/Gemfile.lock) holds them once its definitions load.
#
#   gem install marcel -v 1.1.0
#   ruby src/Campfire.Storage/Media/marcel_magic.rb
gem "marcel", "1.1.0"
require "marcel"

def literal(string) = string.dump

def bytes(value)
  "[#{value.b.bytes.join(", ")}]"
end

# [offset, value, children]: offset is an Integer or an inclusive Range.
def matches(list, indent)
  return " []" if list.nil? || list.empty?
  inner = list.map do |offset, value, children|
    start, stop = offset.is_a?(Range) ? [offset.begin, offset.end] : [offset, "null"]
    "#{indent}    new(#{start}, #{stop}, #{value.nil? ? "null" : bytes(value)},#{matches(children, indent + "    ")}),\n"
  end
  "\n#{indent}[\n#{inner.join}#{indent}]"
end

out = +<<~CS
  // <auto-generated>
  // Generated by src/Campfire.Storage/Media/marcel_magic.rb from marcel #{Marcel::VERSION}. Do not edit.
  // </auto-generated>
  using System.Collections.Frozen;

  namespace Campfire.Storage.Media;

  static partial class Marcel
  {
      /// <summary><c>Marcel::MAGIC</c>: [type, matches], searched in this order.</summary>
      static readonly (string Type, MagicMatch[] Matches)[] Magic =
      [
CS
Marcel::MAGIC.each do |type, list|
  out << "        (#{literal(type)},#{matches(list, "        ")}),\n"
end
out << <<~CS.gsub(/^(?=.)/, "    ")
  ];

  /// <summary><c>Marcel::TYPE_PARENTS</c>: type => parent types.</summary>
  static readonly FrozenDictionary<string, string[]> Parents = new Dictionary<string, string[]>(StringComparer.Ordinal)
  {
CS
Marcel::TYPE_PARENTS.sort.each { |type, parents| out << "        [#{literal(type)}] = [#{Array(parents).map { literal(_1) }.join(", ")}],\n" }
out << "    }.ToFrozenDictionary(StringComparer.Ordinal);\n}\n"

File.write File.join(__dir__, "MarcelMagic.g.cs"), out
