# Generates src/Campfire.Data/Search/WordRanges.cs: the code points Ruby's /[[:word:]]/ matches
# (Onigmo's Unicode tables), as ranges, for SearchQuery's port of SearchesController#query.
#
#   cd tests/Campfire.Data.Tests/Oracle && ruby search_word.rb
#
# It needs the reference's Ruby (reference/.ruby-version): the table changes between Ruby versions
# even at the same Unicode version (Ruby 3.4's Onigmo added the join controls U+200C and U+200D,
# which Ruby 3.3's lacks). SearchQueryTests checks it against reference-rust's, which the reference
# image's Ruby generated.
RUBY = File.read(File.expand_path("../../../reference/.ruby-version", __dir__)).strip
abort "Run with Ruby #{RUBY} (reference/.ruby-version), not #{RUBY_VERSION}" unless RUBY_VERSION == RUBY

ranges = []
(0..0x10FFFF).each do |cp|
  next if cp.between?(0xD800, 0xDFFF)
  next unless [ cp ].pack("U").match?(/[[:word:]]/)
  if ranges.any? && ranges.last[1] == cp - 1
    ranges.last[1] = cp
  else
    ranges << [ cp, cp ]
  end
end

rows = ranges.each_slice(6).map { |slice| "        " + slice.map { |a, b| format("0x%X, 0x%X,", a, b) }.join(" ") }
File.write(File.expand_path("../../../src/Campfire.Data/Search/WordRanges.cs", __dir__), <<~CS)
  // <auto-generated>
  // Generated by tests/Campfire.Data.Tests/Oracle/search_word.rb from Ruby #{RUBY_VERSION} (Unicode
  // #{RbConfig::CONFIG["UNICODE_VERSION"]}): the code points `/[[:word:]]/` matches, as inclusive start, end pairs.
  // </auto-generated>

  namespace Campfire.Data.Searching;

  static class WordRanges
  {
      public static ReadOnlySpan<int> Pairs =>
      [
  #{rows.join("\n")}
      ];
  }
CS
puts "#{ranges.size} ranges"
